### ISSUE TITLE
Page reload after trying to log user that not exist

### ISSUE THREAD

**Issue by KrystianKjjk** [CodersCrew/coderscamp-app#29]
When user provide correct email and password, but it doesnt exist in db, some unnecessary behaviours happends: 
-page is reloaded, (or moved to '/home' probably)
-in localStorage id and token is written but with value "undefind"

Correct behaviour is show snackbar with correct information, that login failed

**Comment by kacper-cyra** [comment]
Possible Duplicate of #18
